#!/usr/bin/env python3

# License MIT
# Copyright 2016-2022 Alex Winkler
# Version 4.0.1

wikibaseurl = 'https://liquipedia.net/'

wikis = [
	'ageofempires',
	'apexlegends',
	'arenafps',
	'arenaofvalor',
	'artifact',
	'autochess',
	'battalion',
	'battlerite',
	'brawlhalla',
	'brawlstars',
	'callofduty',
	'clashroyale',
	'commons',
	'counterstrike',
	'criticalops',
	'crossfire',
	'dota2',
	'fifa',
	'fighters',
	'fortnite',
	'freefire',
	'halo',
	'hearthstone',
	'heroes',
	'leagueoflegends',
	'magic',
	'mobilelegends',
	'naraka',
	'overwatch',
	'paladins',
	'pokemon',
	'pubg',
	'pubgmobile',
	'rainbowsix',
	'rocketleague',
	'runeterra',
	'sideswipe',
	'simracing',
	'smash',
	'splatoon',
	'splitgate',
	'squadrons',
	'starcraft',
	'starcraft2',
	'stormgate',
	'teamfortress',
	'tft',
	'trackmania',
	'underlords',
	'valorant',
	'warcraft',
	'wildrift',
	'worldofwarcraft',
]

lies = [
	'Liquipedia is not awesome... (good that this is a lie ^^)',
	'salle is a young girl',
	'Pizza is bad and no one likes it',
	'salle\'s ideas are always realistic',
	'Chrome is a decent browser',
	'blame swampflare',
	'The revision system of Liquipedia is useless, just kill the history',
	'I played Half Life 3 recently, it sucked',
	'WarCraft 4 is just about to be released',
	'Dota 2 is so tiny, we should focus on big esports like Nokia Snake instead',
	'https://files.catbox.moe/o8tify.gif',
	'Swampflare never laundered memory in his Lithuanian bakery!',
]

wikiroles = {
	'editor': 'Editor',
	'reviewer': 'Reviewer'
}

# Roles the bot can add and remove
botroles = [
	'Age of Empires',
	'Apex Legends',
	'Arena FPS',
	'Arena of Valor',
	'Artifact',
	'Auto Chess',
	'Battalion',
	'Battlerite',
	'Brawl Stars',
	'Brawlhalla',
	'Call of Duty',
	'Clash Royale',
	'Commons',
	'Counter-Strike',
	'Critical Ops',
	'CrossFire',
	'Dota 2',
	'FIFA',
	'Fighters',
	'Fortnite',
	'Free Fire',
	'Halo',
	'Hearthstone',
	'Heroes',
	'League of Legends',
	'Magic',
	'Mobile Legends',
	'Naraka',
	'Overwatch',
	'Paladins',
	'Pokémon',
	'PUBG',
	'PUBG Mobile',
	'Rainbow Six',
	'Rocket League',
	'Runeterra',
	'Sim Racing',
	'Smash',
	'Splatoon',
	'Splitgate',
	'StarCraft 2',
	'StarCraft',
	'Stormgate',
	'Team Fortress',
	'Teamfight Tactics',
	'TrackMania',
	'Underlords',
	'VALORANT',
	'Warcraft',
	'Wild Rift',
	'World of Warcraft',

	'Arabic',
	'Belarusian',
	'Bosnian',
	'Bulgarian',
	'Chinese (Mandarin)',
	'Croatian',
	'Czech',
	'Danish',
	'English (native)',
	'French',
	'German',
	'Hindi',
	'Hungarian',
	'Italian',
	'Japanese',
	'Korean',
	'Macedonian',
	'Mongolian',
	'Norwegian',
	'Polish',
	'Portuguese',
	'Russian',
	'Serbian',
	'Slovak',
	'Slovene',
	'Spanish',
	'Swedish',
	'Tagalog',
	'Thai',
	'Turkish',
	'Ukrainian',
	'Vietnamese',

	'Announcements',
	'CS Predictions',
	'Game Night',
	'Please Ping Me',
	'Random Stats of the Day',
	'R6 Predictions',
	'Templates',
]
